### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by alberk8** [IOTA-NET/IotaWallet.NET#105]
This is a interesting .Net wrapper.   May I know that you must first compile the rust the bindings and this is not included in the nuget package?.   By the way, will it be going to be multi-platform support ie Android, IOS, Linux x64, Linux Arm64?

**Comment by wireless90** [comment]
Hi thanks for your interest. We have to install both nugets explicitly, IotaWallet.Net.Domain and IotaWallet.Net.

 Installing IotaWallet.Net.Domain will add the compiled rust bindings, together with all the neccessary classes that was ported over and also the P/Invokes that talks to the rust bindings


In particular, im leveraging on iotas swift bindings.
Currently i am compiling it myself, in windows for windows, as it seems like IF are focussed on releasing NodeJs bindings first. Official Swift bindings might be released later on. After which it would only make sense to use IF's officially compiled swift bindings and not my own as it might be a security risk.

Yes i am keen in making it work for linux after milestone 1 is complete.  For other architectures perhaps would have to rely on IF.

**Comment by wireless90** [comment]
It now supports linux x64
